"use strict";
(() => {
  const cfg = window.PNW_CONFIG || {};
  const $ = (s) => document.querySelector(s);
  const state = { language: localStorage.getItem("pnw_language") || "en", token: localStorage.getItem("pnw_token") || "", user: null, subscription: null };
  const words = {
    en: { eyebrow:"DAILY NEWS, WITHOUT THE NOISE", headline:"Five stories worth your time.", heroCopy:"A focused English and Urdu news brief, updated by the owner every day.", premiumButton:"Go Premium - Rs 500/month", bonus:"First verified payment: 2 months for the price of 1", today:"TODAY'S TOP FIVE", topStories:"Top stories" },
    ur: { eyebrow:"روزانہ خبریں، بغیر شور کے", headline:"پانچ خبریں جو آپ کے وقت کے قابل ہیں۔", heroCopy:"انگریزی اور اردو میں مختصر خبریں، جو مالک ہر روز اپ ڈیٹ کرتا ہے۔", premiumButton:"پریمیم لیں - 500 روپے ماہانہ", bonus:"پہلی تصدیق شدہ ادائیگی: ایک کی قیمت میں دو ماہ", today:"آج کی پانچ بڑی خبریں", topStories:"اہم خبریں" }
  };
  const escape = (v) => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
  const api = async (path, options = {}) => {
    const base = cfg.API_URL || "/api";
    const res = await fetch(`${base}${path}`, options);
    const data = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(data.error || "Request failed.");
    return data;
  };
  function toast(message, type = "") { const box = $("#toast"); box.textContent = message; box.className = `toast ${type}`; box.classList.remove("hidden"); setTimeout(() => box.classList.add("hidden"), 4800); }
  function renderLanguage() {
    const t = words[state.language]; document.documentElement.lang = state.language; document.documentElement.dir = state.language === "ur" ? "rtl" : "ltr";
    document.querySelectorAll("[data-i18n]").forEach(n => { n.textContent = t[n.dataset.i18n]; });
    $("#languageToggle").textContent = state.language === "en" ? "اردو" : "English";
    localStorage.setItem("pnw_language", state.language); loadNews();
  }
  async function loadNews() {
    const grid = $("#newsGrid"); grid.innerHTML = '<div class="loading-card">Loading today\'s brief...</div>';
    try { const data = await api(`/news?lang=${encodeURIComponent(state.language)}`); const posts = data.posts || []; $("#newsDate").textContent = new Intl.DateTimeFormat(state.language === "ur" ? "ur-PK" : "en-PK", { dateStyle:"medium" }).format(new Date()); grid.innerHTML = posts.length ? posts.map((post,i) => `<article class="news-card"><span class="rank">0${i+1}</span><span class="category">${escape(post.category)}</span><h3${state.language === "ur" ? ' dir="rtl" lang="ur"' : ""}>${escape(state.language === "ur" ? post.title_ur : post.title_en)}</h3><p${state.language === "ur" ? ' dir="rtl" lang="ur"' : ""}>${escape(state.language === "ur" ? post.excerpt_ur : post.excerpt_en)}</p></article>`).join("") : '<div class="loading-card">The owner has not published today\'s five stories yet.</div>'; } catch(e) { grid.innerHTML = `<div class="loading-card error">${escape(e.message)}</div>`; }
  }
  function openModal(html) { const root = $("#modalRoot"); root.innerHTML = `<div class="modal" role="dialog" aria-modal="true"><button class="close" aria-label="Close">×</button>${html}</div>`; root.classList.remove("hidden"); root.querySelector(".close").onclick = closeModal; }
  function closeModal() { const root = $("#modalRoot"); root.classList.add("hidden"); root.innerHTML = ""; }
  function premiumModal() { if (state.user?.isOwner) { openModal(`<h2>Owner / Premium</h2><p>Your owner account has permanent Premium access and Admin permissions.</p><ul class="plan-list"><li>Basic/public mode access</li><li>Premium mode access</li><li>Owner/Admin controls</li><li>Payment verification queue</li><li>News publishing controls</li></ul><button class="primary" id="ownerBasic">View Basic mode</button>`); $("#ownerBasic").onclick = () => { closeModal(); window.scrollTo({top:0,behavior:"smooth"}); toast("Basic/public mode is the normal public view.","success"); }; return; } openModal(`<h2>Premium reading</h2><p>Rs 500 PKR per month. Your first verified payment unlocks two months of Premium access.</p><ul class="plan-list"><li>No ads</li><li>Eye-care colours and premium reading themes</li><li>Better typography and saved preferences</li><li>Priority owner support</li></ul><button class="primary" id="premiumContinue">Continue to payment</button>`); $("#premiumContinue").onclick = () => state.token ? paymentModal() : authModal("signup"); }
  function supportModal() { openModal(`<h2>Owner support</h2><p>For feedback, payment questions, and business support, contact the site owner.</p><div class="payment-method"><b>WhatsApp / Business contact</b><a href="https://wa.me/923425078246" target="_blank" rel="noopener">+92 342 5078246</a></div><div class="payment-method"><b>Email</b><a href="mailto:muzamil.275pk@gmail.com">muzamil.275pk@gmail.com</a></div>`); }
  function normalizePhone(v) { let s = String(v || "").replace(/[\s()-]/g, ""); if (/^03\d{9}$/.test(s)) s = "+92" + s.slice(1); if (/^92\d{10}$/.test(s)) s = "+" + s; return s; }
  function authModal(mode) { const signup = mode === "signup"; openModal(`<h2>${signup ? "Create your account" : "Welcome back"}</h2><p>${signup ? "Create an account with your email." : "Sign in with your email or phone number."}</p><form id="authForm">${signup ? '<label>Name<input name="displayName" maxlength="60" required autocomplete="name"></label>' : ''}<label>${signup ? "Email" : "Email or phone"}<input name="identifier" type="text" required autocomplete="username" placeholder="email@example.com or 0342..." ></label><label>Password<input name="password" type="password" minlength="8" required autocomplete="${signup ? "new-password" : "current-password"}"></label><button class="primary" type="submit">${signup ? "Create account" : "Sign in"}</button></form><p><button class="footer-link" id="authSwitch">${signup ? "Already have an account? Sign in" : "Need an account? Create one"}</button></p>`); $("#authSwitch").onclick = () => authModal(signup ? "signin" : "signup"); $("#authForm").onsubmit = e => submitAuth(e, signup); }
  async function submitAuth(event, signup) { event.preventDefault(); const f = new FormData(event.currentTarget); const identifier = String(f.get("identifier") || "").trim(); const password = String(f.get("password") || ""); const headers = { apikey: cfg.SUPABASE_PUBLISHABLE_KEY, "Content-Type":"application/json" }; const body = signup ? { email: identifier, password, data:{ display_name:String(f.get("displayName") || "").trim() } } : (identifier.includes("@") ? { email:identifier, password } : { phone:normalizePhone(identifier), password }); const endpoint = signup ? "/auth/v1/signup" : "/auth/v1/token?grant_type=password"; try { const r = await fetch(`${cfg.SUPABASE_URL}${endpoint}`, {method:"POST",headers,body:JSON.stringify(body)}); const data = await r.json().catch(()=>({})); if (!r.ok) throw new Error(data.msg || data.error_description || "Authentication failed."); if (!data.access_token) { closeModal(); return toast("Check your email to confirm the account, then sign in.","success"); } state.token=data.access_token; state.user=data.user || null; localStorage.setItem("pnw_token",state.token); closeModal(); await refreshAccount(); toast("Signed in successfully.","success"); } catch(e) { toast(e.message,"error"); } }
  async function refreshAccount() { if (!state.token) { $("#accountButton").textContent="Sign in"; $("#adminPanel").classList.add("hidden"); return; } try { const data = await api("/me", {headers:{Authorization:`Bearer ${state.token}`}}); state.user=data.user; state.subscription=data.subscription; $("#accountButton").textContent=data.user.isOwner ? "Owner / Premium" : data.subscription?.active ? "Premium account" : "My account"; if (data.user.isAdmin || data.user.isOwner) { $("#adminPanel").classList.remove("hidden"); loadPayments(); } } catch(e) { localStorage.removeItem("pnw_token"); state.token=""; state.user=null; $("#accountButton").textContent="Sign in"; $("#adminPanel").classList.add("hidden"); } }
  function paymentModal() { openModal(`<h2>Send payment proof</h2><p>Payment creates provisional Premium access. The owner will verify the transfer.</p><div class="payment-method"><b>Easypaisa</b>+92 342 5078246</div><div class="payment-method"><b>UBL Bank</b>PK91UNIL0109000315081244</div><form id="paymentForm"><label>Payment method<select name="method" required><option value="easypaisa">Easypaisa</option><option value="ubl">UBL Bank</option></select></label><label>Transaction ID<input name="transactionId" minlength="6" maxlength="80" required></label><label>Payment screenshot (JPG, PNG or PDF; max 5 MB)<input name="proof" type="file" accept="image/jpeg,image/png,application/pdf" required></label><button class="primary" type="submit">Activate provisional Premium</button></form>`); $("#paymentForm").onsubmit = submitPayment; }
  async function submitPayment(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const file=form.get("proof"); if (!(file instanceof File) || file.size>5*1024*1024) return toast("Use a JPG, PNG, or PDF below 5 MB.","error"); try { const r=await fetch(`${cfg.API_URL}/payments`,{method:"POST",headers:{Authorization:`Bearer ${state.token}`},body:form}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||"Payment submission failed."); closeModal(); toast(data.message,"success"); await refreshAccount(); } catch(e) { toast(e.message,"error"); } }
  async function loadPayments() { const box=$("#paymentsList"); try { const data=await api("/admin/payments",{headers:{Authorization:`Bearer ${state.token}`}}); box.innerHTML=data.payments.length?data.payments.map(p=>`<div class="payment-item"><b>${escape(p.profiles?.display_name||"Member")}</b> · ${escape(p.payment_method)}<br><small>${escape(p.transaction_id)} · ${escape(p.status)} · ends ${new Date(p.provisional_ends_at).toLocaleDateString()}</small><div class="payment-actions"><button class="approve" data-payment="${p.id}" data-action="approve">Approve</button><button class="reject" data-payment="${p.id}" data-action="reject">Reject</button><button data-payment="${p.id}" data-action="proof">Open proof</button></div></div>`).join(""):"No payment proofs awaiting review."; } catch(e){ box.textContent=e.message; } }
  async function reviewPayment(id,action){ try { if(action==="proof") return window.open(`${cfg.API_URL}/admin/payment?id=${encodeURIComponent(id)}`,"_blank","noopener"); const data=await api(`/admin/payment?id=${encodeURIComponent(id)}`,{method:"PATCH",headers:{Authorization:`Bearer ${state.token}`,"Content-Type":"application/json"},body:JSON.stringify({action})}); toast(`Payment ${action}d.","success"); loadPayments(); } catch(e){ toast(e.message,"error"); } }
  async function publishNews(event){ event.preventDefault(); const f=Object.fromEntries(new FormData(event.currentTarget)); try { await api("/admin/news",{method:"POST",headers:{Authorization:`Bearer ${state.token}`,"Content-Type":"application/json"},body:JSON.stringify(f)}); event.currentTarget.reset(); toast("News card published.","success"); loadNews(); } catch(e){toast(e.message,"error");} }
  document.addEventListener("click",e=>{ const action=e.target.closest("[data-action]")?.dataset.action; if(action==="open-subscribe") premiumModal(); if(action==="open-support") supportModal(); if(e.target.dataset.payment) reviewPayment(e.target.dataset.payment,e.target.dataset.action); });
  $("#languageToggle").onclick=()=>{state.language=state.language==="en"?"ur":"en";renderLanguage();}; $("#accountButton").onclick=()=>state.token?premiumModal():authModal("signin"); $("#refreshPayments").onclick=loadPayments; $("#newsForm").onsubmit=publishNews; $("#year").textContent=new Date().getFullYear();
  renderLanguage(); refreshAccount();
})();
