"use strict";
(() => {
  const c=window.PNW_CONFIG||{},q=s=>document.querySelector(s),S={lang:localStorage.getItem('pnw_language')||'en',mode:localStorage.getItem('pnw_mode')||'basic',token:localStorage.getItem('pnw_token')||'',user:null,sub:null,posts:[]};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x]));
  async function api(path,opt={}){const h=new Headers(opt.headers||{});if(S.token)h.set('Authorization',`Bearer ${S.token}`);const r=await fetch(`${c.API_URL||'/api'}${path}`,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed.');return d;}
  function toast(t,kind=''){const e=q('#toast');e.textContent=t;e.className=`toast ${kind}`;e.classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.add('hidden'),4200);}
  function setMode(m){S.mode=m;localStorage.setItem('pnw_mode',m);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));q('#basicMode').classList.toggle('hidden',m!=='basic');q('#premiumMode').classList.toggle('hidden',m!=='premium');render();}
  function setLang(){document.documentElement.lang=S.lang;document.documentElement.dir=S.lang==='ur'?'rtl':'ltr';q('#languageToggle').textContent=S.lang==='en'?'اردو':'English';localStorage.setItem('pnw_language',S.lang);render();}
  function card(p,premium=false){const ur=S.lang==='ur',title=ur?p.title_ur:p.title_en,text=ur?p.excerpt_ur:p.excerpt_en,img=p.image_url?`<img src="${esc(p.image_url)}" alt="" loading="lazy">`:'';const source=p.source_url&&p.source_name?`<a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">${esc(p.source_name)}</a>`:(p.source_name?esc(p.source_name):'');return `<article class="news-card ${premium?'premium-card':''}">${img}<div class="card-top"><span class="rank">0${p.daily_rank}</span><span class="category">${esc(p.category)}</span></div><h3>${esc(title)}</h3><p>${esc(text)}</p><div class="card-meta"><time>${new Date(p.updated_at||p.published_on).toLocaleDateString(ur?'ur-PK':'en-PK',{dateStyle:'medium'})}</time>${source?`<span>·</span><span>${source}</span>`:''}</div>${premium?'<span class="premium-tag">Premium mode</span>':''}</article>`;}
  function render(){if(S.mode==='basic'){q('#newsGrid').innerHTML=S.posts.length?S.posts.map(p=>card(p)).join(''):'<div class="loading-card">No stories have been published for today yet.</div>';return;}const ok=!!(S.user&&(S.user.isOwner||S.sub?.active));q('#premiumState').textContent=ok?'Premium access is active.':'Premium mode is separate and requires active access.';q('#premiumGrid').innerHTML=ok&&S.posts.length?S.posts.map(p=>card(p,true)).join(''):'<div class="premium-gate"><h3>Premium mode is locked</h3><p>Basic remains public. Premium is a separate reading mode.</p><button class="primary" data-action="subscribe">Unlock Premium</button></div>';}
  async function loadNews(){try{const d=await api(`/news?lang=${S.lang}`);S.posts=d.posts||[];q('#newsDate').textContent=new Date(`${d.date}T12:00:00`).toLocaleDateString(S.lang==='ur'?'ur-PK':'en-PK',{dateStyle:'medium'});render();}catch(e){q('#newsGrid').innerHTML=`<div class="loading-card error">${esc(e.message)}</div>`;}}
  async function refresh(){if(!S.token){render();return;}try{const d=await api('/me');S.user=d.user;S.sub=d.subscription;q('#accountButton').textContent=d.user.isOwner?'Owner / Premium':d.sub?.active?'Premium account':'My account';if(d.user.isAdmin){q('#adminPanel').classList.remove('hidden');loadAdminNews();loadPayments();}render();}catch(e){localStorage.removeItem('pnw_token');S.token='';S.user=null;S.sub=null;q('#accountButton').textContent='Sign in';q('#adminPanel').classList.add('hidden');render();}}
  function modal(html){const r=q('#modalRoot');r.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><button class="close" aria-label="Close">×</button>${html}</div>`;r.classList.remove('hidden');r.setAttribute('aria-hidden','false');r.querySelector('.close').onclick=()=>{r.classList.add('hidden');r.innerHTML='';};}
  function auth(){modal('<h2>Sign in</h2><form id="authForm"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><button class="primary" type="submit">Sign in</button></form>');q('#authForm').onsubmit=login;}
  async function login(e){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await fetch(`${c.SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:String(f.get('email')).trim(),password:String(f.get('password'))})}),d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||'Authentication failed.');S.token=d.access_token;localStorage.setItem('pnw_token',S.token);q('#modalRoot').classList.add('hidden');await refresh();toast('Signed in.','success');}catch(x){toast(x.message,'error');}}
  function subscribe(){if(S.user?.isOwner||S.sub?.active)return setMode('premium');if(!S.token)return auth();modal('<h2>Premium mode</h2><p>First verified payment unlocks two months; later verified payments unlock one month.</p><div class="payment-method"><b>Payment details</b><span>Use the published payment instructions provided by the owner.</span></div><form id="paymentForm"><label>Method<select name="method"><option value="easypaisa">Easypaisa</option><option value="ubl">UBL Bank</option></select></label><label>Transaction ID<input name="transactionId" minlength="6" maxlength="80" required></label><label>Proof<input name="proof" type="file" accept="image/jpeg,image/png,application/pdf" required></label><button class="primary">Submit for verification</button></form>');q('#paymentForm').onsubmit=submitPayment;}
  async function submitPayment(e){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('proof');if(!(file instanceof File)||file.size>5242880)return toast('Proof must be JPG, PNG or PDF under 5 MB.','error');try{const d=await api('/payments',{method:'POST',body:f});q('#modalRoot').classList.add('hidden');toast(d.message,'success');refresh();}catch(x){toast(x.message,'error');}}
  async function loadAdminNews(){try{const d=await api('/admin/news');q('#adminNewsList').innerHTML=d.posts?.length?d.posts.map(p=>`<div class="admin-news-item"><div><b>#${p.daily_rank} ${esc(p.title_en)}</b><small>${esc(p.category)}</small></div><div><button data-edit="${p.id}">Edit</button><button class="reject" data-delete="${p.id}">Delete</button></div></div>`).join(''):'No cards today.';}catch(e){q('#adminNewsList').textContent=e.message;}}
  function fill(p){const f=q('#newsForm');Object.entries({id:p.id,dailyRank:p.daily_rank,category:p.category,titleEn:p.title_en,titleUr:p.title_ur,excerptEn:p.excerpt_en,excerptUr:p.excerpt_ur,imageUrl:p.image_url||'',sourceName:p.source_name||'',sourceUrl:p.source_url||''}).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v;});q('#formTitle').textContent='Edit news';}
  function clearForm(){q('#newsForm').reset();q('#newsForm').elements.id.value='';q('#formTitle').textContent='Publish news';}
  async function saveNews(e){e.preventDefault();const f=new FormData(e.currentTarget),id=String(f.get('id')||''),body=JSON.stringify(Object.fromEntries(f));try{await api(id?`/admin/news?id=${encodeURIComponent(id)}`:'/admin/news',{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body});toast(id?'News updated.':'News published.','success');clearForm();await loadNews();loadAdminNews();}catch(x){toast(x.message,'error');}}
  async function loadPayments(){try{const d=await api('/admin/payments');q('#paymentsList').innerHTML=d.payments?.length?d.payments.map(p=>`<div class="payment-item"><b>${esc(p.method)}</b><small>${esc(p.user_id)} · ${esc(p.transaction_id)} · Rs ${esc(p.amount)}</small><div class="payment-actions"><button class="approve" data-payment="${p.id}" data-action="approve">Approve</button><button class="reject" data-payment="${p.id}" data-action="reject">Reject</button><button data-payment="${p.id}" data-action="proof">Open proof</button></div></div>`).join(''):'No payments awaiting review.';}catch(e){q('#paymentsList').textContent=e.message;}}
  async function reviewPayment(id,a){try{if(a==='proof')return window.open(`${c.API_URL||'/api'}/admin/payment?id=${encodeURIComponent(id)}`,'_blank','noopener');await api(`/admin/payment?id=${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})});toast(`Payment ${a}d.`,'success');loadPayments();refresh();}catch(x){toast(x.message,'error');}}
  document.addEventListener('click',e=>{const m=e.target.closest('[data-mode]');if(m)return setMode(m.dataset.mode);const a=e.target.closest('[data-action]')?.dataset.action;if(a==='subscribe')return subscribe();if(e.target.dataset.payment)return reviewPayment(e.target.dataset.payment,e.target.dataset.action);if(e.target.dataset.edit){const p=S.posts.find(x=>String(x.id)===String(e.target.dataset.edit));if(p)fill(p);}if(e.target.dataset.delete&&confirm('Delete this news card?'))api(`/admin/news?id=${e.target.dataset.delete}`,{method:'DELETE'}).then(()=>{toast('News deleted.','success');loadNews();loadAdminNews();}).catch(x=>toast(x.message,'error'));});
  q('#languageToggle').onclick=()=>{S.lang=S.lang==='en'?'ur':'en';setLang();loadNews();};q('#accountButton').onclick=()=>S.token?setMode('premium'):auth();q('#newsForm').onsubmit=saveNews;q('#resetNews').onclick=clearForm;q('#refreshAdmin').onclick=()=>{loadAdminNews();loadPayments();};q('#year').textContent=new Date().getFullYear();setLang();setMode(S.mode);loadNews();refresh();
})();
