"use strict";
(() => {
  const c=window.PNW_CONFIG||{},q=s=>document.querySelector(s);
  const K={lang:'pnw_language',mode:'pnw_mode',token:'pnw_token',refresh:'pnw_refresh_token',email:'pnw_saved_email',remember:'pnw_remember_login',news:'pnw_news_cache'};
  const S={lang:localStorage.getItem(K.lang)||'en',mode:localStorage.getItem(K.mode)||'basic',token:localStorage.getItem(K.token)||'',refresh:localStorage.getItem(K.refresh)||'',user:null,sub:null,posts:[]};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x]));
  const cached=()=>{try{return JSON.parse(localStorage.getItem(K.news)||'null')}catch{return null}};
  const saveCache=d=>{try{localStorage.setItem(K.news,JSON.stringify({lang:S.lang,date:d.date,posts:d.posts||[],savedAt:Date.now()}))}catch{}};
  async function refreshSession(){if(!S.refresh)return false;try{const r=await fetch(`${c.SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:S.refresh})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)return false;S.token=d.access_token;S.refresh=d.refresh_token||S.refresh;localStorage.setItem(K.token,S.token);localStorage.setItem(K.refresh,S.refresh);return true}catch{return false}}
  async function api(path,opt={},retry=true){const h=new Headers(opt.headers||{});if(S.token)h.set('Authorization',`Bearer ${S.token}`);const r=await fetch(`${c.API_URL||'/api'}${path}`,{...opt,headers:h});if(r.status===401&&retry&&S.refresh&&await refreshSession())return api(path,opt,false);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed.');return d}
  function toast(t,kind=''){const e=q('#toast');e.textContent=t;e.className=`toast ${kind}`;e.classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.add('hidden'),4200)}
  function setMode(m){S.mode=m;localStorage.setItem(K.mode,m);document.body.dataset.mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));q('#basicMode').classList.toggle('hidden',m!=='basic');q('#premiumMode').classList.toggle('hidden',m!=='premium');q('.premium-strip')?.classList.toggle('hidden',m!=='basic');render()}
  function setLang(){document.documentElement.lang=S.lang;document.documentElement.dir=S.lang==='ur'?'rtl':'ltr';q('#languageToggle').textContent=S.lang==='en'?'اردو':'English';localStorage.setItem(K.lang,S.lang);render()}
  function card(p,premium=false){const ur=S.lang==='ur',title=ur?p.title_ur:p.title_en,text=ur?p.excerpt_ur:p.excerpt_en,img=p.image_url?`<img src="${esc(p.image_url)}" alt="" loading="lazy" decoding="async">`:'';const source=p.source_url&&p.source_name?`<a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">${esc(p.source_name)}</a>`:(p.source_name?esc(p.source_name):'');return `<article class="news-card ${premium?'premium-card':''}">${img}<div class="card-top"><span class="rank">0${p.daily_rank}</span><span class="category">${esc(p.category)}</span></div><h3>${esc(title)}</h3><p>${esc(text)}</p><div class="card-meta"><time>${new Date(p.updated_at||p.published_on).toLocaleDateString(ur?'ur-PK':'en-PK',{dateStyle:'medium'})}</time>${source?`<span class="meta-dot">·</span><span>${source}</span>`:''}</div>${premium?'<span class="premium-tag">Premium mode</span>':''}</article>`}
  function render(){if(S.mode==='basic'){q('#newsGrid').innerHTML=S.posts.length?S.posts.map(p=>card(p)).join(''):'<div class="loading-card">No stories have been published for today yet.</div>';q('#newsGrid').setAttribute('aria-busy','false');return}const ok=!!(S.user&&(S.user.isOwner||S.sub?.active));q('#premiumState').textContent=ok?'Premium access is active.':'Premium mode is separate and requires active access.';q('#premiumGrid').innerHTML=ok&&S.posts.length?S.posts.map(p=>card(p,true)).join(''):'<div class="premium-gate"><span class="premium-gate-kicker">Premium access</span><h3>Unlock the full workspace.</h3><p>Basic keeps the briefing focused. Premium adds a richer reading mode built for deeper daily news use.</p><button class="primary" data-action="subscribe">Unlock Premium</button></div>'}
  function showNewsError(){const csh=cached();if(csh?.posts?.length){S.posts=csh.posts;render();toast('Showing cached news while live news is unavailable.','error');return}q('#newsGrid').setAttribute('aria-busy','false');q('#newsGrid').innerHTML='<div class="loading-card error" role="alert"><div class="error-icon" aria-hidden="true">!</div><div><p>Today’s news couldn’t be loaded.</p><span>Please try again.</span></div><button class="secondary" type="button" data-action="retry-news">Retry</button></div>'}
  async function loadNews(){q('#newsGrid').setAttribute('aria-busy','true');const cc=cached();if(cc?.lang===S.lang&&cc?.posts?.length){S.posts=cc.posts;if(cc.date)q('#newsDate').textContent=new Date(`${cc.date}T12:00:00`).toLocaleDateString(S.lang==='ur'?'ur-PK':'en-PK',{dateStyle:'medium'});render()}try{const d=await api(`/news?lang=${S.lang}`);S.posts=d.posts||[];q('#newsDate').textContent=new Date(`${d.date}T12:00:00`).toLocaleDateString(S.lang==='ur'?'ur-PK':'en-PK',{dateStyle:'medium'});saveCache(d);render()}catch{showNewsError()}}
  function closeModal(){const r=q('#modalRoot');r.classList.add('hidden');r.setAttribute('aria-hidden','true');r.innerHTML=''}
  function passwordToggle(form){const input=form?.querySelector('input[name="password"]');if(!input||input.parentElement.querySelector('.password-toggle'))return;const wrap=document.createElement('div');wrap.className='password-wrap';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);const b=document.createElement('button');b.type='button';b.className='password-toggle';b.textContent='Show';b.setAttribute('aria-label','Show password');wrap.appendChild(b);b.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'Hide':'Show';b.setAttribute('aria-label',`${show?'Hide':'Show'} password`)}}
  function modal(html){const r=q('#modalRoot');r.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><button class="close" aria-label="Close">×</button>${html}</div>`;r.classList.remove('hidden');r.setAttribute('aria-hidden','false');r.querySelector('.close').onclick=closeModal;passwordToggle(r.querySelector('form'))}
  function auth(signup=false){const saved=localStorage.getItem(K.email)||'',remember=localStorage.getItem(K.remember)!=='false';modal(`<h2>${signup?'Create your account':'Sign in'}</h2><form id="authForm">${signup?'<label>Name<input name="displayName" maxlength="60" required autocomplete="name"></label>':''}<label>Email<input name="email" type="email" value="${esc(saved)}" required autocomplete="email"></label><label>Password<input name="password" type="password" minlength="8" required autocomplete="${signup?'new-password':'current-password'}"></label>${signup?'':'<label class="remember-row"><input name="remember" type="checkbox" '+(remember?'checked':'')+'> <span>Remember this device</span></label>'}<button class="primary" type="submit">${signup?'Create account':'Sign in'}</button></form><button class="footer-link" id="authSwitch" type="button">${signup?'Already have an account? Sign in':'Need an account? Create one'}</button>`);q('#authSwitch').onclick=()=>auth(!signup);q('#authForm').onsubmit=e=>login(e,signup)}
  async function login(e,signup){e.preventDefault();const f=new FormData(e.currentTarget),email=String(f.get('email')).trim(),remember=signup||f.get('remember')==='on';remember?localStorage.setItem(K.email,email):localStorage.removeItem(K.email);localStorage.setItem(K.remember,String(remember));const body=signup?{email,password:String(f.get('password')),data:{display_name:String(f.get('displayName')).trim()}}:{email,password:String(f.get('password'))};try{const r=await fetch(`${c.SUPABASE_URL}${signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password'}`,{method:'POST',headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.msg||d.error_description||'Authentication failed.');if(!d.access_token){closeModal();return toast('Check your email to confirm the account, then sign in.','success')}S.token=d.access_token;S.refresh=d.refresh_token||'';localStorage.setItem(K.token,S.token);if(S.refresh)localStorage.setItem(K.refresh,S.refresh);closeModal();await refresh();toast('Signed in successfully.','success')}catch(x){toast(x.message,'error')}}
  function subscribe(){if(S.user?.isOwner||S.sub?.active)return setMode('premium');if(!S.token)return auth(true);modal(`<h2>Premium mode</h2><p>Introductory offer: 2 months for the price of 1; later payments unlock one month.</p><div class="payment-method"><b>Easypaisa</b>${esc(c.PAYMENT_EASYPAISA||'See owner payment instructions')}</div><div class="payment-method"><b>UBL Bank</b>${esc(c.PAYMENT_UBL||'See owner payment instructions')}</div><form id="paymentForm"><label>Method<select name="method"><option value="easypaisa">Easypaisa</option><option value="ubl">UBL Bank</option></select></label><label>Transaction ID<input name="transactionId" minlength="6" maxlength="80" required autocomplete="off"></label><label>Proof<input name="proof" type="file" accept="image/jpeg,image/png,application/pdf" required></label><button class="primary">Submit for verification</button></form>`);q('#paymentForm').onsubmit=submitPayment}
  async function submitPayment(e){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('proof');if(!(file instanceof File)||file.size>5242880)return toast('Proof must be JPG, PNG or PDF under 5 MB.','error');try{const d=await api('/payments',{method:'POST',body:f});closeModal();toast(d.message,'success');refresh()}catch(x){toast(x.message,'error')}}
  async function refresh(){if(!S.token){q('#accountButton').textContent='Sign in';q('#adminPanel').classList.add('hidden');render();return}try{const d=await api('/me');S.user=d.user;S.sub=d.subscription;q('#accountButton').textContent=d.user.isOwner?'Owner / Premium':d.sub?.active?'Premium account':'My account';if(d.user.isAdmin){q('#adminPanel').classList.remove('hidden');loadAdminNews();loadPayments()}render()}catch{localStorage.removeItem(K.token);localStorage.removeItem(K.refresh);S.token='';S.refresh='';S.user=null;S.sub=null;q('#accountButton').textContent='Sign in';q('#adminPanel').classList.add('hidden');render()}}
  async function loadAdminNews(){try{const d=await api('/admin/news');q('#adminNewsList').innerHTML=d.posts?.length?d.posts.map(p=>`<div class="admin-news-item"><div><b>#${p.daily_rank} ${esc(p.title_en)}</b><small>${esc(p.category)}</small></div><div><button data-edit="${p.id}">Edit</button><button class="reject" data-delete="${p.id}">Delete</button></div></div>`).join(''):'No cards today.'}catch{q('#adminNewsList').textContent='Owner news area is unavailable.'}}
  function fill(p){const f=q('#newsForm');Object.entries({id:p.id,dailyRank:p.daily_rank,category:p.category,titleEn:p.title_en,titleUr:p.title_ur,excerptEn:p.excerpt_en,excerptUr:p.excerpt_ur,imageUrl:p.image_url||'',sourceName:p.source_name||'',sourceUrl:p.source_url||''}).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});q('#formTitle').textContent='Edit news'}
  function clearForm(){q('#newsForm').reset();q('#newsForm').elements.id.value='';q('#formTitle').textContent='Publish news'}
  async function saveNews(e){e.preventDefault();const f=new FormData(e.currentTarget),id=String(f.get('id')||''),body=JSON.stringify(Object.fromEntries(f));try{await api(id?`/admin/news?id=${encodeURIComponent(id)}`:'/admin/news',{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body});toast(id?'News updated.':'News published.','success');clearForm();await loadNews();loadAdminNews()}catch(x){toast(x.message,'error')}}
  async function loadPayments(){try{const d=await api('/admin/payments');q('#paymentsList').innerHTML=d.payments?.length?d.payments.map(p=>`<div class="payment-item"><b>${esc(p.method)}</b><small>${esc(p.user_id)} · ${esc(p.transaction_id)} · Rs ${esc(p.amount)}</small><div class="payment-actions"><button class="approve" data-payment="${p.id}" data-action="approve">Approve</button><button class="reject" data-payment="${p.id}" data-action="reject">Reject</button><button data-payment="${p.id}" data-action="proof">Open proof</button></div></div>`).join(''):'No payments awaiting review.'}catch{q('#paymentsList').textContent='Payment queue is unavailable.'}}
  async function reviewPayment(id,a){try{if(a==='proof')return window.open(`${c.API_URL||'/api'}/admin/payment?id=${encodeURIComponent(id)}`,'_blank','noopener');await api(`/admin/payment?id=${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})});toast(`Payment ${a}d.`,'success');loadPayments();refresh()}catch(x){toast(x.message,'error')}}
  function support(){const phone=String(c.OWNER_PHONE||'').replace(/[^\d]/g,''),email=String(c.OWNER_EMAIL||'');modal(`<span class="support-kicker">SUPPORT</span><h2>How can we help?</h2><p>Contact support directly for account, payment, access, or feedback questions.</p><div class="payment-method support-card"><b>WhatsApp</b><a class="support-action" href="https://wa.me/${esc(phone)}?text=${encodeURIComponent('Hello, I need help with Punjabi News Workspace.')}" target="_blank" rel="noopener noreferrer">Open WhatsApp</a><small>${esc(c.OWNER_PHONE||'')}</small></div><div class="payment-method support-card"><b>Email</b><a class="support-action" href="mailto:${esc(email)}?subject=Punjabi%20News%20Workspace%20Support">Email support</a><small>${esc(email)}</small></div><button class="secondary" type="button" data-action="copy-support">Copy email address</button>`);q('[data-action="copy-support"]').onclick=async()=>{try{await navigator.clipboard.writeText(email);toast('Support email copied.','success')}catch{toast(email)}}}
  function install(){if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}
  document.addEventListener('click',e=>{const m=e.target.closest('[data-mode]');if(m)return setMode(m.dataset.mode);const a=e.target.closest('[data-action]')?.dataset.action;if(a==='subscribe')return subscribe();if(a==='open-support')return support();if(a==='retry-news')return loadNews();if(a==='copy-support')return;if(e.target.dataset.payment)return reviewPayment(e.target.dataset.payment,e.target.dataset.action);if(e.target.dataset.edit){const p=S.posts.find(x=>String(x.id)===String(e.target.dataset.edit));if(p)fill(p)}if(e.target.dataset.delete&&confirm('Delete this news card?'))api(`/admin/news?id=${e.target.dataset.delete}`,{method:'DELETE'}).then(()=>{toast('News deleted.','success');loadNews();loadAdminNews()}).catch(x=>toast(x.message,'error'))});
  q('#languageToggle').onclick=()=>{S.lang=S.lang==='en'?'ur':'en';setLang();loadNews()};q('#accountButton').onclick=()=>S.token?setMode('premium'):auth(false);q('#newsForm').onsubmit=saveNews;q('#resetNews').onclick=clearForm;q('#refreshAdmin').onclick=()=>{loadAdminNews();loadPayments()};q('#year').textContent=new Date().getFullYear();install();setLang();setMode(S.mode);loadNews();refresh();
})();
