(() => {
  const esc=v=>String(v??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x]));
  const api=path=>fetch(path,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('News unavailable')));
  const localDate=d=>new Date(`${d}T12:00:00`).toLocaleDateString(document.documentElement.lang==='ur'?'ur-PK':'en-PK',{dateStyle:'medium'});
  const dayShift=(date,days)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
  let baseDate='',selectedPage=1;
  const fallbackImage=p=>{const t=`${p.title_en||''} ${p.category||''}`.toLowerCase();if(t.includes('iran')||t.includes('hormuz'))return 'https://image.sggp.org.vn/w1000/Uploaded/2026/dufkxmeyxq/2026_04_17/73ec9725-bd8a-4bf4-9796-ec5a9dd08c44-6543-4845.png.webp';if(t.includes('nepal')||t.includes('flood')||t.includes('tunnel'))return 'https://images.euronews.com/articles/stories/08/05/18/24/1536x864_cmsv2_8291ab88-cd72-56b2-8f12-c19f6cf80fc3-8051824.jpg';if(t.includes('gpt')||t.includes('ai')||t.includes('openai'))return 'https://images.unsplash.com/photo-1589779255718-3c459da9ffeb?auto=format&fit=crop&w=1600&q=80';if(t.includes('gloria')||t.includes('femin'))return 'https://i.natgeofe.com/n/28a4b70e-c4a5-4e15-a038-dbc0bd542181/01-gloria-steinem-difficult-women.jpg';return 'https://www.uccrow.com/wp-content/uploads/2022/03/51714345480_c46f195646_k-2.jpg'};
  function card(p){const ur=document.documentElement.lang==='ur',title=ur?p.title_ur:p.title_en,text=ur?p.excerpt_ur:p.excerpt_en,img=p.image_url||fallbackImage(p),source=p.source_url&&p.source_name?`<a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">${esc(p.source_name)}</a>`:(p.source_name?esc(p.source_name):'');return `<article class="news-card"><img src="${esc(img)}" alt="" loading="lazy" decoding="async"><div class="card-top"><span class="rank">0${p.daily_rank}</span><span class="category">${esc(p.category)}</span></div><h3>${esc(title)}</h3><p>${esc(text)}</p><div class="card-meta"><time>${localDate(p.published_on)}</time>${source?`<span class="meta-dot">·</span><span>${source}</span>`:''}</div></article>`}
  function addStyles(){if(document.getElementById('historyStyles'))return;const s=document.createElement('style');s.id='historyStyles';s.textContent='.history-pagination{display:flex;justify-content:center;align-items:center;gap:8px;flex-wrap:wrap;margin:28px auto 8px}.history-pagination button{min-width:40px;height:40px;border:1px solid rgba(38,32,27,.16);border-radius:999px;background:transparent;color:inherit;font:inherit;font-weight:700;cursor:pointer;transition:transform .2s ease,box-shadow .2s ease,background .2s ease}.history-pagination button:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(0,0,0,.1)}.history-pagination button.active{background:#26201b;color:#fff;border-color:#26201b}.history-pagination .history-label{width:100%;text-align:center;font-size:.78rem;letter-spacing:.08em;text-transform:uppercase;opacity:.62;margin-bottom:2px}.brand-mark .brand-logo{width:100%;height:100%;display:block;object-fit:contain;border-radius:inherit}@media(max-width:520px){.history-pagination{gap:6px;margin-top:22px}.history-pagination button{min-width:38px;height:38px}}@media(prefers-reduced-motion:reduce){.history-pagination button{transition:none}}';document.head.appendChild(s)}
  function setupBrand(){const mark=document.querySelector('.brand-mark');if(mark)mark.innerHTML='<img class="brand-logo" src="/favicon.svg" alt="" aria-hidden="true">';const h=document.querySelector('#today-heading');if(h)h.textContent="Today's five stories."}
  function ensurePagination(){const grid=document.querySelector('#newsGrid');if(!grid)return null;let nav=document.querySelector('#historyPagination');if(!nav){nav=document.createElement('nav');nav.id='historyPagination';nav.className='history-pagination';nav.setAttribute('aria-label','News archive');grid.insertAdjacentElement('afterend',nav)}return nav}
  async function loadPage(page){if(!baseDate)return;selectedPage=page;const date=dayShift(baseDate,-(page-1)),lang=document.documentElement.lang==='ur'?'ur':'en',grid=document.querySelector('#newsGrid');if(!grid)return;grid.setAttribute('aria-busy','true');try{const d=await api(`/api/news?lang=${lang}&date=${date}`);document.querySelector('#newsDate').textContent=localDate(date);grid.innerHTML=d.posts?.length?d.posts.map(card).join(''):`<div class="loading-card">No stories were published for ${esc(localDate(date))}.</div>`;grid.setAttribute('aria-busy','false');document.querySelectorAll('#historyPagination button[data-page]').forEach(b=>{const active=Number(b.dataset.page)===page;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')});window.scrollTo({top:Math.max(0,grid.getBoundingClientRect().top+window.scrollY-100),behavior:'smooth'})}catch{grid.setAttribute('aria-busy','false');grid.innerHTML='<div class="loading-card error" role="alert"><p>News history could not be loaded.</p></div>'}}
  function buildPagination(){const nav=ensurePagination();if(!nav)return;nav.innerHTML='<span class="history-label">News archive</span>'+Array.from({length:7},(_,i)=>`<button type="button" data-page="${i+1}" aria-label="News page ${i+1}">${i+1}</button>`).join('');nav.querySelectorAll('button[data-page]').forEach(b=>b.addEventListener('click',()=>loadPage(Number(b.dataset.page))));nav.querySelector('button[data-page="1"]').classList.add('active');nav.querySelector('button[data-page="1"]').setAttribute('aria-current','page')}
  async function init(){addStyles();setupBrand();try{const d=await api(`/api/news?lang=${document.documentElement.lang==='ur'?'ur':'en'}`);baseDate=d.date;buildPagination()}catch{const date=new Date();baseDate=date.toISOString().slice(0,10);buildPagination()}}
  function bindLanguage(){document.querySelector('#languageToggle')?.addEventListener('click',()=>setTimeout(()=>{const current=document.querySelector('#historyPagination button.active');loadPage(Number(current?.dataset.page||selectedPage));},100))}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>{init();bindLanguage()}):(init(),bindLanguage());
})();
