(() => {
'use strict';
const M={'PREMIUM WORKSPACE':'پریمیم ورک اسپیس','A richer reading experience.':'ایک مزید بہتر مطالعے کا تجربہ۔','Manage Premium':'پریمیم منظم کریں','Deep brief':'تفصیلی بریف','Source context':'ماخذ کی تفصیل','Priority layout':'ترجیحی لے آؤٹ','PREMIUM PREVIEW':'پریمیم پیش نظارہ','Basic stays simple. Premium goes further.':'بنیادی موڈ سادہ رہتا ہے۔ پریمیم مزید آگے جاتا ہے۔','Premium is available separately for readers who want the enhanced experience.':'بہتر تجربہ چاہنے والے قارئین کے لیے پریمیم الگ سے دستیاب ہے۔','Premium mode is separate from Basic mode and requires active access.':'پریمیم موڈ بنیادی موڈ سے الگ ہے اور فعال رسائی درکار ہے۔','Premium access is active.':'پریمیم رسائی فعال ہے۔','Premium access':'پریمیم رسائی','Unlock the full workspace.':'مکمل ورک اسپیس کھولیں۔','Basic keeps the briefing focused. Premium adds a richer reading mode built for deeper daily news use.':'بنیادی موڈ بریفنگ کو مختصر اور مرکوز رکھتا ہے۔ پریمیم روزانہ خبروں کے لیے مزید گہرائی والا مطالعہ موڈ فراہم کرتا ہے۔','Unlock Premium':'پریمیم کھولیں','Premium mode':'پریمیم موڈ'};
const q=s=>document.querySelector(s),urdu=()=>document.documentElement.lang==='ur';
function localize(){document.querySelectorAll('#premiumMode .eyebrow,#premiumMode h2,#premiumMode h3,#premiumMode .muted,#premiumMode .premium-toolbar span,#premiumMode button,#premium-anchor .eyebrow,#premium-anchor h2,#premium-anchor .muted,#premium-anchor button').forEach(el=>{const original=el.dataset.premiumEn||el.textContent.trim();el.dataset.premiumEn=original;el.textContent=urdu()?(M[original]||original):original})}
function animate(el,keyframes,options={}){if(!el)return;try{el.getAnimations().forEach(a=>a.cancel())}catch{}el.style.opacity='';el.style.transform='';el.style.filter='';return el.animate(keyframes,{duration:options.duration||900,delay:options.delay||0,easing:'cubic-bezier(.2,.72,.2,1)',fill:'both'})}
function trigger(root,preview=false){const r=root||q(preview?'#premium-anchor':'#premiumMode');if(!r)return;localize();requestAnimationFrame(()=>{const e=r.querySelector('.eyebrow'),h=r.querySelector('h2'),muted=r.querySelector('.muted'),btn=r.querySelector('button');animate(e,[{opacity:0,transform:'translate3d(0,-28px,0)'},{opacity:1,transform:'none'}],{duration:750});animate(h,[{opacity:0,transform:'translate3d(-32px,0,0)'},{opacity:1,transform:'none'}],{duration:800,delay:80});animate(muted,[{opacity:0,transform:'translate3d(0,24px,0)'},{opacity:1,transform:'none'}],{duration:750,delay:180});animate(btn,[{opacity:0,transform:'translate3d(28px,0,0)'},{opacity:1,transform:'none'}],{duration:800,delay:260});if(!preview)r.querySelectorAll('.premium-toolbar span').forEach((x,i)=>animate(x,[{opacity:0,transform:`translate3d(0,${i%2?-18:18}px,0)`},{opacity:1,transform:'none'}],{duration:650,delay:320+i*90}));if(!preview)r.querySelectorAll('.premium-card').forEach((x,i)=>animate(x,[{opacity:0,transform:`translate3d(${i%2?-22:22}px,${i%3===1?18:0}px,0) scale(.985)`},{opacity:1,transform:'none'}],{duration:800,delay:430+i*100}));})}
const obs=new MutationObserver(m=>{if(m.some(x=>x.type==='attributes'&&x.attributeName==='data-mode')){if(document.body.dataset.mode==='premium')setTimeout(()=>trigger(q('#premiumMode')),20)}});
obs.observe(document.body,{attributes:true,attributeFilter:['data-mode']});
document.addEventListener('click',e=>{const target=e.target instanceof Element?e.target:null;if(!target)return;if(target.closest?.('#premium-anchor button'))setTimeout(()=>trigger(q('#premium-anchor'),true),40);if(target.closest?.('a[href="#premium-anchor"]'))setTimeout(()=>trigger(q('#premium-anchor'),true),40);if(target.closest?.('#languageToggle'))setTimeout(localize,40)},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',localize,{once:true});else localize();
})();
