(() => {
'use strict';
const EMAIL='muzamil.275pk@gmail.com', FALLBACK_IMAGE='/news-images/fallback.svg';
const qs=s=>document.querySelector(s), lang=()=>localStorage.getItem('pnw_language')||'en', isUrdu=()=>lang()==='ur';
const esc=v=>String(v??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x]));
const fmtDate=d=>new Date(`${d}T12:00:00`).toLocaleDateString(isUrdu()?'ur-PK':'en-PK',{dateStyle:'medium'});
const state={dates:[],selected:null,loading:false,posts:[]};
const newsTop=()=>qs('#today-heading')||qs('.news-section')||qs('#newsGrid');
function installLayout(){if(qs('#pnw-layout-fixes'))return;const s=document.createElement('style');s.id='pnw-layout-fixes';s.textContent=`html{scroll-behavior:smooth;scroll-padding-top:92px}#newsGrid,#premiumGrid{scroll-margin-top:92px}.news-grid,.premium-grid{overflow:visible}.news-card .news-image-wrap{width:100%;display:flex;justify-content:center;align-items:center;margin:0 0 20px;overflow:hidden}.news-card .news-image-wrap img{display:block;width:100%!important;max-width:100%!important;height:auto!important;aspect-ratio:16/9;object-fit:cover;margin:0!important;position:static!important}.premium-card .news-image-wrap{display:flex;justify-content:center}.premium-mode{overflow:visible}.premium-strip{scroll-margin-top:92px}body[data-mode="premium"] .premium-strip{display:none!important}.workspace-overlay{max-height:calc(100dvh - 32px);overflow:auto;-webkit-overflow-scrolling:touch}.news-pager{scroll-margin-top:92px}.news-grid{visibility:hidden}.brand-logo{display:block;width:150px;height:40px;max-width:42vw;object-fit:contain}`;document.head.appendChild(s)}
function reveal(){const g=qs('#newsGrid');if(g)g.style.visibility='visible'}
function goToNewsTop(){const target=newsTop();if(!target)return;setTimeout(()=>{const header=qs('.site-header');const y=Math.max(0,target.getBoundingClientRect().top+window.scrollY-(header?.getBoundingClientRect().height||78)-12);window.scrollTo({top:y,behavior:'smooth'})},60)}
function pager(){let el=qs('#newsPager');if(!el){el=document.createElement('nav');el.id='newsPager';el.className='news-pager';el.setAttribute('aria-label','News editions');const section=qs('.news-section');if(section)section.appendChild(el)}if(!state.dates.length){el.innerHTML='';return}el.innerHTML=state.dates.slice(0,12).map((date,i)=>`<button type="button" class="news-page ${date===state.selected?'active':''}" data-news-date="${esc(date)}" aria-label="News edition ${i+1}, ${esc(fmtDate(date))}" aria-current="${date===state.selected?'page':'false'}"><span>${i+1}</span><small>${esc(fmtDate(date))}</small></button>`).join('');el.querySelectorAll('[data-news-date]').forEach(b=>b.addEventListener('click',()=>loadEdition(b.dataset.newsDate,true)))}
function card(p,premium=false){const title=isUrdu()?p.title_ur:p.title_en,text=isUrdu()?p.excerpt_ur:p.excerpt_en,src=p.image_url||FALLBACK_IMAGE;const img=`<div class="news-image-wrap"><img src="${esc(src)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='${FALLBACK_IMAGE}'"></div>`;const source=p.source_url&&p.source_name?`<a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">${esc(p.source_name)}</a>`:esc(p.source_name||'');return `<article class="news-card ${premium?'premium-card':''} workspace-card" data-history-title="${esc(title)}">${img}<div class="card-top"><span class="rank">0${esc(p.daily_rank)}</span><span class="category">${esc(p.category)}</span></div><h3>${esc(title)}</h3><p>${esc(text)}</p><div class="card-meta"><time>${esc(fmtDate(p.published_on))}</time>${source?`<span class="meta-dot">·</span><span>${source}</span>`:''}</div>${premium?'<span class="premium-tag">Premium mode</span>':''}</article>`}
function syncPremiumEdition(){if(document.body?.dataset.mode!=='premium')return;const grid=qs('#premiumGrid');if(!grid||grid.querySelector('.premium-gate')||!state.posts.length)return;grid.innerHTML=state.posts.map(p=>card(p,true)).join('')}
function resetGemini(){const m=qs('#geminiMessages'),p=qs('#geminiPrompt'),s=qs('#geminiStatus');if(m)m.innerHTML='<div class="gemini-empty">Ask for today\'s news, a summary of a story, or a comparison of the available workspace stories.</div>';if(p){p.value='';p.disabled=false}if(s)s.textContent='';qs('#geminiAsk')?.removeAttribute('disabled')}
function appendGemini(role,text){const box=qs('#geminiMessages');if(!box)return;box.querySelector('.gemini-empty')?.remove();const item=document.createElement('div');item.className=`gemini-message ${role}`;item.innerHTML=`<span class="gemini-role">${role==='user'?'You':'Gemini'}</span><div class="gemini-text">${esc(text).replace(/\n/g,'<br>')}</div>`;box.appendChild(item);box.scrollTop=box.scrollHeight}
async function askGemini(e){e.preventDefault();const p=qs('#geminiPrompt'),b=qs('#geminiAsk'),value=p?.value.trim();if(!value||document.body?.dataset.mode!=='premium')return;b?.setAttribute('disabled','disabled');if(p)p.disabled=true;appendGemini('user',value);try{const token=localStorage.getItem('pnw_token')||'',r=await fetch('/api/gemini',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({prompt:value}),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Gemini could not complete the request.');appendGemini('assistant',d.text||'Gemini returned an empty response.');window.dispatchEvent(new CustomEvent('pnw:gemini-asked',{detail:{prompt:value,response:d.text||'',newsDate:d.newsDate||state.selected}}));if(p)p.value=''}catch(error){appendGemini('assistant',error.message||'Gemini request failed.')}finally{b?.removeAttribute('disabled');if(p)p.disabled=false}}
async function loadEdition(date,shouldScroll=false){if(!date||state.loading)return;state.loading=true;state.selected=date;pager();const grid=qs('#newsGrid');if(grid){grid.setAttribute('aria-busy','true');grid.innerHTML='<article class="loading-card skeleton-card"><span></span><span></span><span></span></article>'}try{const r=await fetch(`/api/news?lang=${encodeURIComponent(lang())}&date=${encodeURIComponent(date)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'News unavailable');state.dates=Array.isArray(d.availableDates)?d.availableDates:state.dates;state.selected=d.date||date;state.posts=Array.isArray(d.posts)?d.posts:[];pager();if(grid){grid.innerHTML=state.posts.map(p=>card(p)).join('')||'<div class="loading-card">No stories were published for this edition.</div>';grid.setAttribute('aria-busy','false');reveal()}const dateEl=qs('#newsDate');if(dateEl)dateEl.textContent=fmtDate(state.selected);localStorage.setItem('pnw_selected_news_date',state.selected);syncPremiumEdition();window.dispatchEvent(new CustomEvent('pnw:news-edition',{detail:{date:state.selected,posts:state.posts}}));if(shouldScroll)goToNewsTop()}catch(e){if(grid){grid.setAttribute('aria-busy','false');grid.style.visibility='visible';grid.innerHTML='<div class="loading-card error" role="alert"><div><p>Couldn’t load this edition.</p><span>Please try again.</span></div><button class="secondary" type="button" id="retryEdition">Retry</button></div>';qs('#retryEdition')?.addEventListener('click',()=>loadEdition(date,true))}}finally{state.loading=false}}
async function initEditions(){try{const r=await fetch(`/api/news?lang=${encodeURIComponent(lang())}`,{cache:'no-store'}),d=await r.json();if(!r.ok)return;state.dates=Array.isArray(d.availableDates)?d.availableDates:[];const latest=d.date||state.dates[0];state.selected=latest;localStorage.setItem('pnw_selected_news_date',latest||'');pager();if(latest)await loadEdition(latest,false);else reveal()}catch{reveal()}}
function scrollToNews(){const basicButton=qs('.mode-switch [data-mode="basic"]');if(document.body?.dataset.mode!=='basic')basicButton?.click();goToNewsTop()}
function openOverlay(kind){const root=qs('#modalRoot');if(!root)return;const premium=kind==='premium';root.innerHTML=`<div class="modal workspace-overlay" role="dialog" aria-modal="true" aria-labelledby="workspace-overlay-title"><button class="close" type="button" aria-label="Close">×</button><span class="auth-premium-kicker">${premium?'PREMIUM PREVIEW':'SUPPORT'}</span><h2 id="workspace-overlay-title">${premium?'See what Premium adds.':'Need help? We’re here.'}</h2>${premium?`<p class="overlay-lead">A richer reading workspace without changing the simple Basic briefing.</p><div class="preview-feature-grid"><div><b>Deep brief</b><span>More context around each daily story.</span></div><div><b>Source context</b><span>Cleaner source details and easier reading.</span></div><div><b>Priority layout</b><span>A focused Premium workspace for deeper reading.</span></div></div><button class="primary" type="button" data-overlay-subscribe>Open Premium</button>`:`<p class="overlay-lead">For Premium, account, payment, news or website issues, contact us directly.</p><div class="support-contact"><b>Email support</b><a href="mailto:${EMAIL}">${EMAIL}</a><button class="secondary" type="button" data-copy-email>Copy email</button></div>`}</div>`;root.classList.remove('hidden');root.setAttribute('aria-hidden','false');const close=()=>{root.classList.add('hidden');root.setAttribute('aria-hidden','true');root.innerHTML=''};root.querySelector('.close').onclick=close;root.querySelector('[data-copy-email]')?.addEventListener('click',async e=>{try{await navigator.clipboard.writeText(EMAIL);e.currentTarget.textContent='Copied';setTimeout(()=>e.currentTarget.textContent='Copy email',1400)}catch{location.href=`mailto:${EMAIL}`}});root.querySelector('[data-overlay-subscribe]')?.addEventListener('click',()=>{close();document.querySelector('[data-action="subscribe"]')?.click()})}
function bind(){document.addEventListener('click',e=>{const today=e.target.closest('.main-nav a[href="#newsGrid"]');if(today){e.preventDefault();scrollToNews();return}const support=e.target.closest('[data-action="open-support"]');if(support){e.preventDefault();openOverlay('support');return}const preview=e.target.closest('#premium-anchor .primary');if(preview){e.preventDefault();openOverlay('premium');return}});qs('#geminiForm')?.addEventListener('submit',askGemini);qs('#geminiClear')?.addEventListener('click',resetGemini);document.addEventListener('pnw:language-changed',()=>setTimeout(initEditions,100));document.addEventListener('pnw:premium-render',syncPremiumEdition);let previousMode=document.body?.dataset.mode||'basic';const observer=new MutationObserver(()=>{const mode=document.body?.dataset.mode||'basic';if(mode!==previousMode&&mode==='premium')resetGemini();previousMode=mode;if(mode==='premium')syncPremiumEdition()});observer.observe(document.body,{attributes:true,attributeFilter:['data-mode']})}
function start(){installLayout();bind();const footer=qs('footer');if(footer&&!footer.querySelector('.support-email'))footer.insertAdjacentHTML('afterbegin',`<span class="support-email"><span>Support:</span> <a href="mailto:${EMAIL}">${EMAIL}</a></span>`);setTimeout(initEditions,0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
