interface Env { PAYMENT_PROOFS: R2Bucket; FRONTEND_ORIGIN: string; SUPABASE_URL: string; SUPABASE_ANON_KEY: string; SUPABASE_SERVICE_ROLE_KEY: string; ADMIN_USER_ID?: string; OWNER_EMAIL?: string; OWNER_PHONE?: string; TURNSTILE_SECRET?: string; }
type User = { id: string; email?: string; phone?: string; user_metadata?: { display_name?: string } };
const json = (body: unknown, status = 200, headers: Record<string, string> = {}) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json; charset=utf-8", ...headers } });
const error = (message: string, status = 400, headers: Record<string, string> = {}) => json({ error: message }, status, headers);
const allowedMethods = "GET,POST,PATCH,OPTIONS";
function cors(request: Request, env: Env) { const origin = request.headers.get("origin"); return origin && origin === env.FRONTEND_ORIGIN ? { "access-control-allow-origin": origin, "vary": "Origin", "access-control-allow-headers": "authorization, content-type", "access-control-allow-methods": allowedMethods } : {}; }
function safeText(value: unknown, limit: number) { return typeof value === "string" && value.trim() && value.trim().length <= limit ? value.trim() : null; }
async function supabase(env: Env, path: string, init: RequestInit = {}) { const headers = new Headers(init.headers); headers.set("apikey", env.SUPABASE_SERVICE_ROLE_KEY); headers.set("authorization", `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`); if (!headers.has("content-type") && init.body) headers.set("content-type", "application/json"); return fetch(`${env.SUPABASE_URL}/rest/v1/${path}`, { ...init, headers }); }
async function getUser(request: Request, env: Env): Promise<User | null> { const authorization = request.headers.get("authorization"); if (!authorization?.startsWith("Bearer ")) return null; const response = await fetch(`${env.SUPABASE_URL}/auth/v1/user`, { headers: { apikey: env.SUPABASE_ANON_KEY, authorization } }); return response.ok ? response.json() as Promise<User> : null; }
async function requireUser(request: Request, env: Env, headers: Record<string, string>) { const user = await getUser(request, env); return user || error("Please sign in first.", 401, headers); }
function isResponse(value: unknown): value is Response { return value instanceof Response; }
function normalizePhone(value: string | undefined) { return (value || "").replace(/[^0-9+]/g, "").replace(/^00/, "+"); }
function isAdmin(user: User, env: Env) { const emailMatch = Boolean(env.OWNER_EMAIL && user.email && user.email.trim().toLowerCase() === env.OWNER_EMAIL.trim().toLowerCase()); const phoneMatch = Boolean(env.OWNER_PHONE && user.phone && normalizePhone(user.phone) === normalizePhone(env.OWNER_PHONE)); const idMatch = Boolean(env.ADMIN_USER_ID && user.id === env.ADMIN_USER_ID); return idMatch || emailMatch || phoneMatch; }
async function verifyTurnstile(token: FormDataEntryValue | null, request: Request, env: Env) { if (!env.TURNSTILE_SECRET) return true; if (typeof token !== "string" || !token) return false; const form = new FormData(); form.set("secret", env.TURNSTILE_SECRET); form.set("response", token); form.set("remoteip", request.headers.get("cf-connecting-ip") || ""); const response = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", { method: "POST", body: form }); const result = await response.json() as { success?: boolean }; return result.success === true; }
function extFor(file: File) { return file.type === "image/jpeg" ? "jpg" : file.type === "image/png" ? "png" : file.type === "application/pdf" ? "pdf" : ""; }
function karachiDate() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const pick = (type: string) => parts.find((part) => part.type === type)?.value || ""; return `${pick("year")}-${pick("month")}-${pick("day")}`; }

async function publicNews(url: URL, env: Env, headers: Record<string, string>) {
  const response = await supabase(env, "news_posts?is_published=eq.true&select=id,category,title_en,title_ur,excerpt_en,excerpt_ur,published_on,daily_rank&order=published_on.desc,daily_rank.asc&limit=5");
  if (!response.ok) return error("News is temporarily unavailable.", 503, headers);
  return json({ posts: await response.json(), language: url.searchParams.get("lang") === "ur" ? "ur" : "en" }, 200, headers);
}
async function me(request: Request, env: Env, headers: Record<string, string>) {
  const user = await requireUser(request, env, headers); if (isResponse(user)) return user;
  const owner = isAdmin(user, env);
  const response = await supabase(env, `subscriptions?user_id=eq.${encodeURIComponent(user.id)}&select=plan,status,access_ends_at&limit=1`); const subscriptions = response.ok ? await response.json() as Array<{ plan: string; status: string; access_ends_at: string }> : [];
  const subscription = subscriptions[0];
  const active = owner || Boolean(subscription && new Date(subscription.access_ends_at).getTime() > Date.now() && ["provisional", "active"].includes(subscription.status));
  const ownerSubscription = owner && !subscription ? { plan: "premium", status: "active", access_ends_at: "2099-12-31T23:59:59.999Z" } : subscription;
  return json({ user: { id: user.id, email: user.email, phone: user.phone, isAdmin: owner }, subscription: ownerSubscription ? { ...ownerSubscription, active } : null }, 200, headers);
}
async function createPayment(request: Request, env: Env, headers: Record<string, string>) {
  const user = await requireUser(request, env, headers); if (isResponse(user)) return user;
  const form = await request.formData(); if (!(await verifyTurnstile(form.get("turnstileToken"), request, env))) return error("Security verification failed. Please retry.", 403, headers);
  const method = form.get("method"), transactionId = safeText(form.get("transactionId"), 80), proof = form.get("proof");
  if ((method !== "easypaisa" && method !== "ubl") || !transactionId || !/^[A-Za-z0-9-]+$/.test(transactionId) || !(proof instanceof File) || proof.size > 5 * 1024 * 1024 || !extFor(proof)) return error("Use a valid transaction ID and a JPG, PNG, or PDF proof under 5 MB.", 422, headers);
  const existing = await supabase(env, `subscriptions?user_id=eq.${encodeURIComponent(user.id)}&select=access_ends_at,status&limit=1`); const current = existing.ok ? (await existing.json() as Array<{ access_ends_at: string; status: string }>)[0] : null;
  if (current && new Date(current.access_ends_at).getTime() > Date.now() && ["provisional", "active"].includes(current.status)) return error("Your Premium access is already active.", 409, headers);
  const queue = await supabase(env, `payment_submissions?user_id=eq.${encodeURIComponent(user.id)}&status=eq.provisional&select=id&limit=1`); if (queue.ok && (await queue.json() as unknown[]).length) return error("You already have a proof awaiting owner verification.", 409, headers);
  const profileResult = await supabase(env, `profiles?id=eq.${encodeURIComponent(user.id)}&select=first_payment_bonus_used&limit=1`); const profile = profileResult.ok ? (await profileResult.json() as Array<{ first_payment_bonus_used: boolean }>)[0] : null;
  const months = profile?.first_payment_bonus_used ? 1 : 2; const ends = new Date(); ends.setMonth(ends.getMonth() + months); const key = `proofs/${user.id}/${crypto.randomUUID()}.${extFor(proof)}`;
  await env.PAYMENT_PROOFS.put(key, await proof.arrayBuffer(), { httpMetadata: { contentType: proof.type, contentDisposition: "attachment" }, customMetadata: { userId: user.id, transactionId } });
  const payment = await supabase(env, "payment_submissions", { method: "POST", headers: { prefer: "return=representation" }, body: JSON.stringify({ user_id: user.id, payment_method: method, transaction_id: transactionId, receipt_object_key: key, status: "provisional", amount_pkr: 500, provisional_ends_at: ends.toISOString() }) });
  if (!payment.ok) { await env.PAYMENT_PROOFS.delete(key); return error("Could not save payment proof. Please try again.", 503, headers); }
  const subscription = await supabase(env, "subscriptions?on_conflict=user_id", { method: "POST", headers: { prefer: "resolution=merge-duplicates,return=representation" }, body: JSON.stringify({ user_id: user.id, plan: "premium", status: "provisional", access_ends_at: ends.toISOString() }) });
  if (!subscription.ok) return error("Proof saved, but Premium activation needs owner help. Please contact support.", 503, headers);
  return json({ message: `Premium is active provisionally until ${ends.toLocaleDateString("en-PK")}. The owner will verify your payment.` }, 201, headers);
}
async function listPayments(request: Request, env: Env, headers: Record<string, string>) { const user = await requireUser(request, env, headers); if (isResponse(user)) return user; if (!isAdmin(user, env)) return error("Owner access required.", 403, headers); const response = await supabase(env, "payment_submissions?status=eq.provisional&select=id,payment_method,transaction_id,status,provisional_ends_at,created_at,profiles(display_name)&order=created_at.asc"); return response.ok ? json({ payments: await response.json() }, 200, headers) : error("Payment queue unavailable.", 503, headers); }
async function reviewPayment(request: Request, id: string, env: Env, headers: Record<string, string>) {
  const user = await requireUser(request, env, headers); if (isResponse(user)) return user; if (!isAdmin(user, env)) return error("Owner access required.", 403, headers); const body = await request.json() as { action?: string }; if (body.action !== "approve" && body.action !== "reject") return error("Invalid review action.", 422, headers);
  const found = await supabase(env, `payment_submissions?id=eq.${encodeURIComponent(id)}&select=id,user_id,status&limit=1`); const payment = found.ok ? (await found.json() as Array<{ id: string; user_id: string; status: string }>)[0] : null; if (!payment || payment.status !== "provisional") return error("This payment cannot be reviewed.", 404, headers);
  const status = body.action === "approve" ? "approved" : "rejected"; await supabase(env, `payment_submissions?id=eq.${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ status, reviewed_at: new Date().toISOString(), reviewed_by: user.id }) });
  if (body.action === "approve") { await supabase(env, `subscriptions?user_id=eq.${encodeURIComponent(payment.user_id)}`, { method: "PATCH", body: JSON.stringify({ status: "active" }) }); await supabase(env, `profiles?id=eq.${encodeURIComponent(payment.user_id)}`, { method: "PATCH", body: JSON.stringify({ first_payment_bonus_used: true }) }); }
  else await supabase(env, `subscriptions?user_id=eq.${encodeURIComponent(payment.user_id)}`, { method: "PATCH", body: JSON.stringify({ status: "cancelled", access_ends_at: new Date().toISOString() }) });
  return json({ ok: true, status }, 200, headers);
}
async function proof(request: Request, id: string, env: Env, headers: Record<string, string>) { const user = await requireUser(request, env, headers); if (isResponse(user)) return user; if (!isAdmin(user, env)) return error("Owner access required.", 403, headers); const lookup = await supabase(env, `payment_submissions?id=eq.${encodeURIComponent(id)}&select=receipt_object_key&limit=1`); const item = lookup.ok ? (await lookup.json() as Array<{ receipt_object_key: string }>)[0] : null; if (!item) return error("Proof not found.", 404, headers); const object = await env.PAYMENT_PROOFS.get(item.receipt_object_key); if (!object) return error("Proof file not found.", 404, headers); return new Response(object.body, { headers: { ...headers, "content-type": object.httpMetadata?.contentType || "application/octet-stream", "content-disposition": object.httpMetadata?.contentDisposition || "attachment" } }); }
async function createNews(request: Request, env: Env, headers: Record<string, string>) { const user = await requireUser(request, env, headers); if (isResponse(user)) return user; if (!isAdmin(user, env)) return error("Owner access required.", 403, headers); const data = await request.json() as Record<string, unknown>; const category = safeText(data.category, 40), titleEn = safeText(data.titleEn, 160), titleUr = safeText(data.titleUr, 160), excerptEn = safeText(data.excerptEn, 500), excerptUr = safeText(data.excerptUr, 500), rank = Number(data.dailyRank); if (!category || !titleEn || !titleUr || !excerptEn || !excerptUr || !Number.isInteger(rank) || rank < 1 || rank > 5) return error("Complete every bilingual news field and use a rank from 1 to 5.", 422, headers); const response = await supabase(env, "news_posts", { method: "POST", body: JSON.stringify({ category, title_en: titleEn, title_ur: titleUr, excerpt_en: excerptEn, excerpt_ur: excerptUr, daily_rank: rank, published_on: karachiDate(), is_published: true, published_by: user.id }) }); return response.ok ? json({ ok: true }, 201, headers) : error("That rank is already used today, or publishing failed.", 409, headers); }

export default { async fetch(request: Request, env: Env): Promise<Response> { const headers = cors(request, env); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers }); const url = new URL(request.url); try { if (request.method === "GET" && url.pathname === "/news") return publicNews(url, env, headers); if (request.method === "GET" && url.pathname === "/me") return me(request, env, headers); if (request.method === "POST" && url.pathname === "/payments") return createPayment(request, env, headers); if (request.method === "GET" && url.pathname === "/admin/payments") return listPayments(request, env, headers); if (request.method === "POST" && url.pathname === "/admin/news") return createNews(request, env, headers); const match = url.pathname.match(/^\/admin\/payments\/([0-9a-f-]{36})(?:\/(proof))?$/i); if (match && request.method === "PATCH" && !match[2]) return reviewPayment(request, match[1], env, headers); if (match && request.method === "GET" && match[2] === "proof") return proof(request, match[1], env, headers); return error("Not found.", 404, headers); } catch (cause) { console.error("Worker error", cause); return error("Unexpected server error.", 500, headers); } } };