const crypto = require('crypto');
function json(res, body, status = 200) { res.statusCode = status; res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.end(JSON.stringify(body)); }
function getEnv() { const env = { SUPABASE_URL: process.env.SUPABASE_URL, SUPABASE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY, SUPABASE_AUTH_KEY: process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY, OWNER_EMAIL: (process.env.OWNER_EMAIL || '').toLowerCase(), OWNER_PHONE: process.env.OWNER_PHONE || '' }; if (!env.SUPABASE_URL || !env.SUPABASE_KEY || !env.SUPABASE_AUTH_KEY) throw new Error('Supabase environment variables are not configured.'); if (!env.OWNER_EMAIL && !env.OWNER_PHONE) throw new Error('Owner authorization is not configured.'); return env; }
function cors(req, res) { const origin = req.headers.origin; const allowed = process.env.FRONTEND_ORIGIN; if (origin && allowed && origin === allowed) { res.setHeader('Access-Control-Allow-Origin', origin); res.setHeader('Vary', 'Origin'); } res.setHeader('Access-Control-Allow-Headers', 'authorization, content-type'); res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PATCH,DELETE,OPTIONS'); }
async function supabaseFetch(path, init = {}) { const env = getEnv(); const { authHeader, headers: initHeaders, ...requestInit } = init; const headers = new Headers(initHeaders || {}); headers.set('apikey', env.SUPABASE_KEY); headers.set('Authorization', authHeader || `Bearer ${env.SUPABASE_KEY}`); if (requestInit.body && !headers.has('content-type') && !(requestInit.body instanceof ArrayBuffer) && !Buffer.isBuffer(requestInit.body)) headers.set('content-type', 'application/json'); return fetch(`${env.SUPABASE_URL}/rest/v1/${path}`, { ...requestInit, headers }); }
async function getUser(req) { const env = getEnv(); const auth = req.headers.authorization || ''; if (!auth.startsWith('Bearer ')) return null; const response = await fetch(`${env.SUPABASE_URL}/auth/v1/user`, { headers: { apikey: env.SUPABASE_AUTH_KEY, Authorization: auth } }); if (!response.ok) return null; return response.json(); }
function isOwner(user) { const env = getEnv(); const emailMatch = Boolean(env.OWNER_EMAIL && user?.email && user.email.toLowerCase() === env.OWNER_EMAIL); const phoneMatch = Boolean(env.OWNER_PHONE && user?.phone && user.phone === env.OWNER_PHONE); return emailMatch || phoneMatch; }
async function requireUser(req, res) { const user = await getUser(req); if (!user) { json(res, { error: 'Please sign in first.' }, 401); return null; } return user; }
async function dbJson(response) { return response.json().catch(() => ({})); }
function karachiDate() { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Karachi', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const get = type => parts.find(p => p.type === type)?.value || ''; return `${get('year')}-${get('month')}-${get('day')}`; }
function safeText(value, limit) { return typeof value === 'string' && value.trim() && value.trim().length <= limit ? value.trim() : null; }
function safeUrl(value, allowHttp = false) { if (!value) return null; try { const url = new URL(String(value).trim()); return (allowHttp ? ['http:','https:'] : ['https:']).includes(url.protocol) ? url.toString() : null; } catch { return null; } }
function parseMultipartBuffer(buffer, contentType) { const match = /boundary=([^;]+)/i.exec(contentType || ''); if (!match) throw new Error('Invalid multipart form data.'); const boundary = Buffer.from(`--${match[1].replace(/^\"|\"$/g, '')}`); const fields = {}; const files = []; let cursor = 0; while (true) { const start = buffer.indexOf(boundary, cursor); if (start < 0) break; const after = start + boundary.length; if (buffer.slice(after, after + 2).toString() === '--') break; let partStart = after; if (buffer.slice(partStart, partStart + 2).toString() === '\r\n') partStart += 2; const headerEnd = buffer.indexOf(Buffer.from('\r\n\r\n'), partStart); if (headerEnd < 0) break; const rawHeaders = buffer.slice(partStart, headerEnd).toString('utf8'); const bodyStart = headerEnd + 4; const next = buffer.indexOf(boundary, bodyStart); if (next < 0) break; let bodyEnd = next; if (buffer.slice(bodyEnd - 2, bodyEnd).toString() === '\r\n') bodyEnd -= 2; const disposition = /content-disposition:\s*form-data;\s*([^\r\n]+)/i.exec(rawHeaders)?.[1] || ''; const name = /name="([^"]+)"/i.exec(disposition)?.[1]; const filename = /filename="([^"]*)"/i.exec(disposition)?.[1]; const mime = /content-type:\s*([^\r\n]+)/i.exec(rawHeaders)?.[1]?.trim() || 'application/octet-stream'; if (name) { if (filename) files.push({ name, filename, contentType: mime, data: buffer.slice(bodyStart, bodyEnd) }); else fields[name] = buffer.slice(bodyStart, bodyEnd).toString('utf8'); } cursor = next; } return { fields, files }; }
async function readRawBody(req) { const chunks = []; for await (const chunk of req) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); return Buffer.concat(chunks); }
async function parseRequestBody(req) { const raw = await readRawBody(req); const contentType = req.headers['content-type'] || ''; if (contentType.includes('multipart/form-data')) return parseMultipartBuffer(raw, contentType); const text = raw.toString('utf8'); return { fields: text ? JSON.parse(text) : {}, files: [] }; }
function randomName(ext) { return `${crypto.randomUUID()}.${ext}`; }
async function uploadProof(objectPath, file, authHeader) { const env = getEnv(); const path = objectPath.split('/').map(encodeURIComponent).join('/'); const response = await fetch(`${env.SUPABASE_URL}/storage/v1/object/payment-proofs/${path}`, { method: 'POST', headers: { apikey: env.SUPABASE_KEY, Authorization: authHeader, 'Content-Type': file.contentType, 'x-upsert': 'false' }, body: file.data }); if (!response.ok) throw new Error('Could not save payment proof.'); }
async function deleteProof(objectPath, authHeader) { const env = getEnv(); const path = objectPath.split('/').map(encodeURIComponent).join('/'); await fetch(`${env.SUPABASE_URL}/storage/v1/object/payment-proofs/${path}`, { method: 'DELETE', headers: { apikey: env.SUPABASE_KEY, Authorization: authHeader } }); }
module.exports = { json, cors, supabaseFetch, dbJson, getUser, isOwner, requireUser, karachiDate, safeText, safeUrl, parseRequestBody, uploadProof, deleteProof, randomName, getEnv };
