(() => {
'use strict';
const EMAIL='muzamil.275pk@gmail.com';
const FALLBACK_IMAGE='/news-images/fallback.svg';
const qs=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const lang=()=>localStorage.getItem('pnw_language')||'en';
const isUrdu=()=>lang()==='ur';
const fmtDate=d=>new Date(`${d}T12:00:00`).toLocaleDateString(isUrdu()?'ur-PK':'en-PK',{dateStyle:'medium'});
const state={dates:[],selected:null,loading:false,posts:[]};
function scrollNewsTop(){const target=qs('#today-heading')||qs('#newsGrid')||qs('.news-section');if(target) target.scrollIntoView({behavior:'smooth',block:'start'});}
function pager(){let el=qs('#newsPager');if(!el){el=document.createElement('nav');el.id='newsPager';el.className='news-pager';el.setAttribute('aria-label','News editions');const section=qs('.news-section');if(section)section.appendChild(el);}if(!state.dates.length){el.innerHTML='';return;}el.innerHTML=state.dates.slice(0,12).map((date,i)=>`<button type="button" class="news-page ${date===state.selected?'active':''}" data-news-date="${esc(date)}" aria-label="News edition ${i+1}, ${esc(fmtDate(date))}" aria-current="${date===state.selected?'page':'false'}"><span>${i+1}</span><small>${esc(fmtDate(date))}</small></button>`).join('');el.querySelectorAll('[data-news-date]').forEach(b=>b.addEventListener('click',()=>loadEdition(b.dataset.newsDate,true)));}
function card(p,premium=false){const ur=isUrdu();const title=ur?p.title_ur:p.title_en;const text=ur?p.excerpt_ur:p.excerpt_en;const src=p.image_url||FALLBACK_IMAGE;return `<article class="news-card ${premium?'premium-card':''} workspace-card" data-history-title="${esc(title)}"><div class="news-image-wrap"><img src="${esc(src)}" alt="" loading="lazy" decoding="async" onerror="this.onerror=null;this.src='${FALLBACK_IMAGE}'"></div><div class="card-top"><span class="rank">0${esc(p.daily_rank)}</span><span class="category">${esc(p.category)}</span></div><h3>${esc(title)}</h3><p>${esc(text)}</p><div class="card-meta"><time>${esc(fmtDate(p.published_on))}</time>${p.source_url&&p.source_name?`<span class="meta-dot">·</span><span><a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">${esc(p.source_name)}</a></span>`:''}</div>${premium?'<span class="premium-tag">Premium mode</span>':''}</article>`;}
function syncPremiumEdition(){if(document.body?.dataset.mode!=='premium')return;const grid=qs('#premiumGrid');if(grid&&state.posts.length)grid.innerHTML=state.posts.map(p=>card(p,true)).join('');}
function resetGemini(){const m=qs('#geminiMessages'),p=qs('#geminiPrompt'),s=qs('#geminiStatus');if(m)m.innerHTML='<div class="gemini-empty">Ask for today\'s news, a summary of a story, or a comparison of the available workspace stories.</div>';if(p){p.value='';p.disabled=false;}if(s)s.textContent='';qs('#geminiAsk')?.removeAttribute('disabled');}
async function askGemini(e){e.preventDefault();const p=qs('#geminiPrompt'),s=qs('#geminiStatus'),b=qs('#geminiAsk'),value=p?.value.trim();if(!value||document.body?.dataset.mode!=='premium')return;b?.setAttribute('disabled','disabled');if(p)p.disabled=true;if(s)s.textContent='Thinking…';appendGemini('user',value);try{const token=localStorage.getItem('pnw_token')||'';const r=await fetch('/api/gemini',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({prompt:value}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Gemini could not complete the request.');appendGemini('assistant',d.text||'Gemini returned an empty response.');window.dispatchEvent(new CustomEvent('pnw:gemini-asked',{detail:{prompt:value,response:d.text||'',newsDate:d.newsDate||state.selected}}));if(p)p.value='';if(s)s.textContent=d.newsDate?`Based on workspace edition ${fmtDate(d.newsDate)}.`:'';}catch(err){appendGemini('assistant',err.message||'Gemini request failed.');if(s)s.textContent='Request failed.';}finally{b?.removeAttribute('disabled');if(p)p.disabled=false;}}
function appendGemini(role,text){const box=qs('#geminiMessages');if(!box)return;box.querySelector('.gemini-empty')?.remove();const item=document.createElement('div');item.className=`gemini-message ${role}`;item.innerHTML=`<span class="gemini-role">${role==='user'?'You':'Gemini'}</span><div class="gemini-text">${esc(text).replace(/\n/g,'<br>')}</div>`;box.appendChild(item);box.scrollTop=box.scrollHeight;}
async function loadEdition(date,shouldScroll=false){if(!date||state.loading)return;state.loading=true;state.selected=date;pager();const grid=qs('#newsGrid');if(grid){grid.setAttribute('aria-busy','true');grid.innerHTML='<article class="loading-card skeleton-card"><span></span><span></span><span></span></article>';}try{const r=await fetch(`/api/news?lang=${encodeURIComponent(lang())}&date=${encodeURIComponent(date)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'News unavailable');state.dates=Array.isArray(d.availableDates)?d.availableDates:state.dates;state.selected=d.date||date;state.posts=Array.isArray(d.posts)?d.posts:[];pager();if(grid){grid.innerHTML=state.posts.map(p=>card(p)).join('')||'<div class="loading-card">No stories were published for this edition.</div>';grid.setAttribute('aria-busy','false');}const dateEl=qs('#newsDate');if(dateEl)dateEl.textContent=fmtDate(state.selected);localStorage.setItem('pnw_selected_news_date',state.selected);syncPremiumEdition();window.dispatchEvent(new CustomEvent('pnw:news-edition',{detail:{date:state.selected,posts:state.posts}}));if(shouldScroll)setTimeout(scrollNewsTop,60);}catch(err){if(grid){grid.setAttribute('aria-busy','false');grid.innerHTML='<div class="loading-card error" role="alert"><div><p>Couldn’t load this edition.</p><span>Please try again.</span></div><button class="secondary" type="button" id="retryEdition">Retry</button></div>';qs('#retryEdition')?.addEventListener('click',()=>loadEdition(date,true));}}finally{state.loading=false;}}
async function initEditions(){try{const r=await fetch(`/api/news?lang=${encodeURIComponent(lang())}`,{cache:'no-store'});const d=await r.json();if(!r.ok)return;state.dates=Array.isArray(d.availableDates)?d.availableDates:[];const latest=d.date||state.dates[0];state.selected=latest;localStorage.setItem('pnw_selected_news_date',latest||'');pager();if(latest)await loadEdition(latest,false);}catch{}}
function scrollToNews(){const basic=qs('.mode-switch [data-mode="basic"]');if(document.body?.dataset.mode!=='basic')basic?.click();setTimeout(scrollNewsTop,100);}
function bind(){document.addEventListener('click',e=>{const today=e.target.closest('.main-nav a[href="#newsGrid"]');if(today){e.preventDefault();scrollToNews();return;}});qs('#geminiForm')?.addEventListener('submit',askGemini);qs('#geminiClear')?.addEventListener('click',resetGemini);document.addEventListener('pnw:language-changed',()=>setTimeout(initEditions,100));document.addEventListener('pnw:premium-render',syncPremiumEdition);let prev=document.body?.dataset.mode||'basic';new MutationObserver(()=>{const mode=document.body?.dataset.mode||'basic';if(mode!==prev&&mode==='premium')resetGemini();prev=mode;if(mode==='premium')syncPremiumEdition();}).observe(document.body,{attributes:true,attributeFilter:['data-mode']});}
function start(){bind();setTimeout(initEditions,300);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
